CREATE TABLE raw_tweets (
	tw_id nvarchar(60),
	tw_created_at nvarchar(60),
	tw_text nvarchar(250),
	tw_full_text nvarchar(250),
	tw_truncated nvarchar(10),
	tw_reply_id nvarchar(60),
	tw_user_id nvarchar(60),
	tw_user_name nvarchar(60),
	tw_user_verified nvarchar(60),
	tw_user_follower nvarchar(60),
	tw_location nvarchar(60),
	tw_quoted_status_id nvarchar(60),
	tw_is_quote_status nvarchar(10),
	tw_qu_id nvarchar(60),
	tw_qu_created_at nvarchar(60),
	tw_qu_text nvarchar(250),
	tw_qu_full_text nvarchar(250),
	tw_qu_truncated nvarchar(10),
	tw_qu_user_id nvarchar(60),
	tw_qu_user_name nvarchar(60),
	tw_qu_user_verified nvarchar(60),
	tw_qu_user_follower nvarchar(60),
	tw_rt_id nvarchar(60),
	tw_rt_created_at nvarchar(60),
	tw_rt_text nvarchar(250),
	tw_rt_full_text nvarchar(250),
	tw_rt_truncated nvarchar(10),
	tw_rt_user_id nvarchar(60),
	tw_rt_user_name nvarchar(60),
	tw_rt_user_verified nvarchar(60),
	tw_rt_user_follower nvarchar(60),
)

GO